name: pinact

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  pinact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Validate pinned actions
        id: pinact
        continue-on-error: true
        uses: suzuki-shunsuke/pinact-action@49cbd6acd0dbab6a6be2585d1dbdaa43b4410133 # v1.0.0
        with:
          skip_push: "true"
        # pinact-action reports results via GitHub check; we interpret outcome below
      - name: Suggest remediation when pinact fails
        if: steps.pinact.outcome == "failure"
        run: |
          echo '::error::Some GitHub Actions are not pinned to commit SHAs.'
          echo '::error::Fix steps:'
          echo '::error::1. Install pinact (brew install pinact).'
          echo '::error::2. Run \`pinact run\` or \`pinact run -u\` locally to update SHAs.'
          echo '::error::3. Commit the changes and push again.'
          exit 1
